- hosts: localhost
  connection: local
  roles:
  vars:
    - docker_compose: yes
  roles:
     - drhelius.docker

  tasks:
  # Upgrade pip with pip to fix angstwad/docker.ubuntu/pull/35 and docker-py/issues/525
  # Install latest version when no specific release is set.
  - name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
    pip:
      name: "{{ item.name }}"
      state: "{{ item.version }}"
    with_items:
      - { name: pip, version: "latest", install: true }
      - { name: setuptools, version: "latest", install: true }
      - { name: docker-py, version: "latest", install: true }
      - { name: docker-compose, version: "latest", install: true }
      - { name: docker, version: "latest", install: true }
      - { name: requests, version: "latest", install: true }
    when: ( item.install )
    ignore_errors: yes

